name: woluni_park
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  assets:
  - assets/
  - assets/images/
  - assets/Fonts/Bakbak_One
  - assets/Fonts/Lato
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Fonts/Lato/Lato-Regular.ttf
        - asset: assets/Fonts/Lato/Lato-Bold.ttf
          weight: 700
    - family: Bakbak_One
      fonts:
        - asset: assets/Fonts/Bakbak_One/._BakbakOne-Regular.ttf
